export default defineAppConfig({
  title: "NuxtVuetifyTemplate",
  theme: {
    dark: false,
    colors: {
      primary: "#0E5A4A",
      secondary: "#1C8A6A",
      accent: "#C9A227",
      info: "#1C6EA4",
      success: "#2E7D32",
      warning: "#D17B0F",
      error: "#B42318",
      background: "#F5F7F6",
      surface: "#FFFFFF",
      "on-primary": "#FFFFFF",
      "on-secondary": "#FFFFFF",
      "on-accent": "#1B1F24",
      "on-background": "#1F2A2A",
      "on-surface": "#1F2A2A",
    },
    darkColors: {
      primary: "#5AC8A8",
      secondary: "#3FB992",
      accent: "#E0C15A",
      info: "#4DA3DC",
      success: "#59B75D",
      warning: "#E7A23B",
      error: "#F26D6D",
      background: "#0F1A19",
      surface: "#162624",
      "on-primary": "#06231D",
      "on-secondary": "#06231D",
      "on-accent": "#1B1F24",
      "on-background": "#E6F2EF",
      "on-surface": "#E6F2EF",
    },
  },
});
